variables:
  MY_ENV_FILE: .env.ci
  CONTEXT_MODE: "TEST"

etl:
  script:
    - cp .env.ci .env
    - docker build . --tag fairificator 
    - docker compose --env-file $MY_ENV_FILE up --abort-on-container-exit 
