etl:
  script:
    - pwd
    - ls -al /builds/padme-development/external/better/data-cataloging/etl
    - ls -al /builds/padme-development/external/better/data-cataloging/etl/datasets
    - cp .env.ci .env
    - cat .env
    - export CONTEXT_MODE="TEST"
    - docker build . --tag fairificator 
    - docker compose up --abort-on-container-exit 
