etl:
  image: docker:25.0-git
  services:
    - docker:27.5-dind
  script:
    - pwd
#    - ls -al /builds/padme-development/external/better/data-cataloging/etl
#    - ls -al /builds/padme-development/external/better/data-cataloging/etl/datasets
#    - ls -al /builds/padme-development/external/better/data-cataloging/etl/datasets/test
#    - cat /builds/padme-development/external/better/data-cataloging/etl/.env.ci
#    - cat .env.ci
#    - cat /builds/padme-development/external/better/data-cataloging/etl/datasets/test/extr-metadata-phen.csv
    - export CONTEXT_MODE="TEST"
    - export ETL_ENV_FILE_NAME=.env.ci
    - export ABSOLUTE_PATH_ENV_FILE=/builds/padme-development/external/better/data-cataloging/etl/.env.ci
    - docker build . --tag ietl
    - docker compose --env-file ${ABSOLUTE_PATH_ENV_FILE} up --exit-code-from ietl --remove-orphans 
    - docker compose --env-file ${ABSOLUTE_PATH_ENV_FILE} down
    
    # generate the TAR archive of I-ETL
    - echo "email/login/name $GITLAB_USER_EMAIL/$GITLAB_USER_LOGIN/$GITLAB_USER_NAME"
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "$GITLAB_USER_NAME"
    - git config --global -l

    # transform pipeline git url to use our project access token name and credentials
    - git remote -v
    - url_host=`git remote get-url origin | sed -e "s/https:\/\/gitlab-ci-token:.*@//g"`
    - echo https://for-ci-cd:${KEY_TAR_IETL}@${url_host}
    - git remote set-url origin "https://for-ci-cd:${KEY_TAR_IETL}@${url_host}"
    - git remote -v

    # get latest from branch
    - echo git checkout of branch ${CI_COMMIT_REF_NAME}
    - git fetch --all && git checkout ${CI_COMMIT_REF_NAME}
    - git branch --list
    - git remote show
    - git pull origin
    # - git remote show origin
    # - git pull HEAD #${CI_COMMIT_REF_NAME}
    # - echo git pull -r origin ${CI_COMMIT_REF_NAME}
    # - git remote show origin
    # - git pull -r origin ${CI_COMMIT_REF_NAME}
    - git pull origin ${CI_COMMIT_REF_NAME}

    # take artifact from previous job, create timestamped file in reports directory
    - docker save ietl > the-ietl-image.tar

    # add, commit, and push new file (skip any workflow)
    - git status
    - git add the-ietl-image.tar
    - git commit -m "Generated latest TAR image of I-ETL"
    - git push -o ci.skip