#etl:
#  image: docker:25.0-git
#  services:
#    - docker:27.5-dind
#  script:
#    - pwd
#    - export CONTEXT_MODE="TEST"
#    - export ETL_ENV_FILE_NAME=.env.ci
#    - export ABSOLUTE_PATH_ENV_FILE=/builds/padme-development/external/better/data-cataloging/etl/.env.ci
    #- docker build . --tag ietl
    #- docker compose --env-file ${ABSOLUTE_PATH_ENV_FILE} up --exit-code-from ietl --remove-orphans 
    #- docker compose --env-file ${ABSOLUTE_PATH_ENV_FILE} down

docker-build:
  image: docker:cli
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - echo "$CI_REGISTRY_IMAGE"
    - echo "$CI_COMMIT_REF_SLUG"
    - echo "$CI_REGISTRY_USER"
    - echo "$CI_REGISTRY_PASSWORD"
    - echo "$CI_REGISTRY"
    - echo "$DOCKER_IMAGE_NAME"
    - docker build --pull -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"
    - echo "$CI_COMMIT_BRANCH"
    - echo "$CI_DEFAULT_BRANCH"
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
        docker push "$CI_REGISTRY_IMAGE:latest"
      fi
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile


# to upload a single file to the artifacts:
# PUT /projects/:id/packages/generic/:package_name/:package_version/:file_name
# :id: Your project ID or URL-encoded path
# :package_name: Name of your package
# :package_version: Version of your package
# :file_name: Name of the file you're uploading

#publish:
#  stage: deploy
#  image: docker:27.5-dind
#  before_script:
#    - apk add --no-cache curl
#  script:
#    - ETL_IMAGE_NAME="the-ietl-image.tar"
#    - docker save ietl > ${ETL_IMAGE_NAME}
#    - ls -al
#    - echo ${CI_API_V4_URL}
#    - echo ${CI_JOB_TOKEN}
#    - echo ${ETL_IMAGE_NAME}
#    - echo ${CI_PROJECT_ID}
#    - echo ${CI_COMMIT_TAG}
#    - echo "'${CI_COMMIT_TAG}'"
#    - >
#      if [ -z "${CI_COMMIT_TAG}" ]; then
#        echo "No tag"
#        THE_TAG_VERSION="0.0"
#      else
#        echo "The tagged version is ${CI_COMMIT_TAG}"
#        THE_TAG_VERSION=${CI_COMMIT_TAG}
#      fi
#    - echo ${THE_TAG_VERSION}
#    - echo "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/etl_package/${THE_TAG_VERSION}/${ETL_IMAGE_NAME}"
#    - |
#      curl --location --header "JOB_TOKEN: ${CI_JOB_TOKEN}" \
#           --upload-file ${ETL_IMAGE_NAME} \
#           "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/etl_package/${THE_TAG_VERSION}/${ETL_IMAGE_NAME}"
