etl:
  script:
    - cp .env.ci .env
    - export CONTEXT_MODE=TEST
    - export MY_ENV_FILE=.env.ci
    - docker build . --tag fairificator 
    - docker compose --env-file ${MY_ENV_FILE} up --abort-on-container-exit 
