etl:
  image: docker:25.0-git
  services:
    - docker:27.5-dind
  script:
    - pwd
#    - ls -al /builds/padme-development/external/better/data-cataloging/etl
#    - ls -al /builds/padme-development/external/better/data-cataloging/etl/datasets
#    - ls -al /builds/padme-development/external/better/data-cataloging/etl/datasets/test
#    - cat /builds/padme-development/external/better/data-cataloging/etl/.env.ci
#    - cat .env.ci
#    - cat /builds/padme-development/external/better/data-cataloging/etl/datasets/test/extr-metadata-phen.csv
    - export CONTEXT_MODE="TEST"
    - export ETL_ENV_FILE_NAME=.env.ci
    - export ABSOLUTE_PATH_ENV_FILE=/builds/padme-development/external/better/data-cataloging/etl/.env.ci
    - docker build . --tag ietl
    - docker compose --env-file ${ABSOLUTE_PATH_ENV_FILE} up --exit-code-from ietl --remove-orphans 
    - docker compose --env-file ${ABSOLUTE_PATH_ENV_FILE} down