etl:
  image: docker:25.0-git
  services:
    - docker:27.5-dind
  script:
    - pwd
    - ls -al /builds/padme-development/external/better/data-cataloging/etl
    - ls -al /builds/padme-development/external/better/data-cataloging/etl/datasets
    - cp .env.ci .env
    - cat .env
    - export CONTEXT_MODE="TEST"
    - export MY_ENV_FILE=.env.test
    - docker build . --tag etl
    - docker compose --env-file .env.test up --exit-code-from etl || true
    - docker compose --env-file .env.test down