#etl:
#  image: docker:25.0-git
#  services:
#    - docker:27.5-dind
#  script:
#    - pwd
#    - export CONTEXT_MODE="TEST"
#    - export ETL_ENV_FILE_NAME=.env.ci
#    - export ABSOLUTE_PATH_ENV_FILE=/builds/padme-development/external/better/data-cataloging/etl/.env.ci
    #- docker build . --tag ietl
    #- docker compose --env-file ${ABSOLUTE_PATH_ENV_FILE} up --exit-code-from ietl --remove-orphans 
    #- docker compose --env-file ${ABSOLUTE_PATH_ENV_FILE} down

docker-build:
  image: docker:cli
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - echo "$CI_REGISTRY_IMAGE"
    - echo "$CI_COMMIT_REF_SLUG"
    - echo "$CI_REGISTRY_USER"
    - echo "$CI_REGISTRY_PASSWORD"
    - echo "$CI_REGISTRY"
    - echo "$DOCKER_IMAGE_NAME"
    - docker build --pull -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"
    - echo "$CI_COMMIT_BRANCH"
    - echo "$CI_DEFAULT_BRANCH"
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        echo "will tag version with latest"
        docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
        echo "will push latest"
        docker push "$CI_REGISTRY_IMAGE:latest"
      fi