from enums.EnumAsClass import EnumAsClass


class ParameterKeys(EnumAsClass):
    # this corresponds to (almost) all the keys defined in the .env
    HOSPITAL_NAME = "HOSPITAL_NAME"
    DB_NAME = "DB_NAME"
    DB_DROP = "DB_DROP"
    DB_UPSERT_POLICY = "DB_UPSERT_POLICY"
    USE_EN_LOCALE = "USE_EN_LOCALE"
    IS_EXTRACT = "EXTRACT"
    IS_ANALYZE = "ANALYZE"
    IS_TRANSFORM = "TRANSFORM"
    IS_LOAD = "LOAD"
    COLUMNS_TO_REMOVE_KEY = "COLUMNS_TO_REMOVE"
    EXPOSE_COMPLETE_DATES_KEY = "EXPOSE_COMPLETE_DATES"
    METADATA_PATH = "METADATA"
    DIAGNOSIS_CLASSIFICATION = "DIAGNOSIS_CLASSIFICATION"
    DIAGNOSIS_REGEXES = "DIAGNOSIS_REGEXES"
    LABORATORY_PATHS = "LABORATORY"
    DIAGNOSIS_PATHS = "DIAGNOSIS"
    MEDICINE_PATHS = "MEDICINE"
    IMAGING_PATHS = "IMAGING"
    GENOMIC_PATHS = "GENOMIC"
    ANONYMIZED_PATIENT_IDS = "ANONYMIZED_PIDS"
