ZIGOSITY2VAR = {"Heterozygous": 0.5, "Homozygous": 0.4, "Hemizygous": 0.1}
INHERITANCE = {"Dominant": 0.5, "Recessive": 0.5}
CONSANGUINITY = {"No": 0.8, "Yes": 0.1, "No information": 0.1}
AFFECTED_RELATIVES = {"No": 0.6, "Yes": 0.3, "No information": 0.1}
WALK_INDEPENDENTLY = {"No": 0.3, "Yes": 0.6, "No information": 0.1}
SPEAK_INDEPENDENTLY = {"No": 0.3, "Yes": 0.6, "No information": 0.1}
DEVELOPMENTAL_DISORDER = {"No": 0.3, "Yes": 0.6, "No information": 0.1}
INTELECTUAL_DISABILITY = {"No": 0.3, "Yes": 0.6, "No information": 0.1}
AUTISM_SPECTRUM_DISORDER = {"No": 0.3, "Yes": 0.6, "No information": 0.1}
ATENTION_DEFICIT_HIPERACTIVITY = {"No": 0.3, "Yes": 0.6, "No information": 0.1}
LANGUAGE_ABSENCE = {"No": 0.3, "Yes": 0.6, "No information": 0.1}
PHOTO_AVAILABLE = {"No": 0.3, "Yes": 0.6, "No information": 0.1}
WESTERN_BLOT = {"Increase": 0.3, "Decrease": 0.3, "No significant": 0.3, "No information": 0.3}
QPCR = {"Increase": 0.3, "Decrease": 0.3, "No significant": 0.3, "No information": 0.3}
FLUORESCENCE_INTENSITY = {"Increase": 0.3, "Decrease": 0.3, "No significant": 0.3, "No information": 0.3}
PROTEIN_INTERACTION = {"Increase": 0.3, "Decrease": 0.3, "No significant": 0.3, "No information": 0.3}
SUBCELLULAR_LOCATION = {"No": 0.4, "Yes": 0.4, "No information": 0.2}
CELLULAR_MORPHOLOGY = {"No": 0.4, "Yes": 0.4, "No information": 0.2}
SPLICING = {"No": 0.4, "Yes": 0.4, "No information": 0.2}
METADOME = {"Tolerant": 0.2, "Slightly tolerant": 0.2, "Neutral": 0.2, "Slightly intolerant": 0.2, "Intolerant": 0.2}
MISSENSE_3D = {"Damage": 0.4, "No damage": 0.4, "-": 0.2}
DYNAMUT = {"Stablishing": 0.5, "Destablishing": 0.5}
ACMG = {"Benign": 0.2, "Likely benign": 0.2, "VUS": 0.2, "Likely pathogenic": 0.2, "Pathogenic": 0.2}
ZYGOSITY = {"heterozygosis": 0.2, "homozygosis": 0.2, "compound heterozygote": 0.2, "hemizygote": 0.2, "mosaic": 0.2}
